---
- name: Create user
  become: true
  user:
    name: "{{ item.name }}"
    state: present
    createhome: yes
  with_items: "{{ users_list }}"
  register: created_user

- name: Add user to sudoers file
  lineinfile:
    path: /etc/sudoers
    line: "{{ item.name }} ALL=(ALL) NOPASSWD:ALL"
    validate: 'visudo -cf %s'
    state: present
  with_items: "{{ created_users.results }}"
  when: created_user.results | length > 0

- name: Copy SSH keys to authorized_keys
  become: true
  authorized_key:
    user: "{{ item.name }}"
    key: "{{ item.ssh_key }}"
  with_items: "{{ ssh_keys }}"
  when: created_user.results | length > 0
