---
- name: Install K3S-agent worker node
  ansible.builtin.shell: |+
    curl -sfL https://get.k3s.io | INSTALL_K3S_CHANNEL={{ k3s_version }} K3S_TOKEN={{ k3s_token }} K3S_URL=https://{{ k3s_master_node }}:6443 sh - 
      