---
- name: Import get_master_token task
  import_tasks: "{{ role_path }}/tasks/get_master_token.yml"

- name: Add system parameters to sysctl.conf
  ansible.builtin.blockinfile:
    path: /etc/sysctl.conf
    block: |
      vm.overcommit_memory = 1
      kernel.panic = 10
    marker: "# {mark} ANSIBLE MANAGED BLOCK - K3S SYSTEM PARAMETERS"

- name: Apply sysctl settings
  ansible.builtin.command: sysctl -p

- name: Import K3S-agent installation task and install
  import_tasks: "{{ role_path }}/tasks/install_k3s-agent.yml"
      
- name: Enable and start K3S-agent service
  ansible.builtin.service:
    name: k3s-agent
    state: started
    enabled: true
