---
- name: Create user
  become: true
  user:
    name: "{{ item.name }}"
    state: present
    createhome: yes
  with_items: "{{ users_list }}"
  register: created_users

- name: Add user to sudoers file
  lineinfile:
    path: /etc/sudoers
    line: "{{ item.name }} ALL=(ALL) NOPASSWD:ALL"
    validate: 'visudo -cf %s'
    state: present
  with_items: "{{ created_users.results }}"
  when: created_users.results | length > 0

- name: Ensure .ssh directory exists
  file:
    path: "/home/{{ item.name }}/.ssh"
    state: directory
    owner: "{{ item.name }}"
    group: "{{ item.name }}"
    mode: "0700"
  with_items: "{{ created_users.results }}"
  when: created_users.results | length > 0

- name: Generate SSH keys
  ansible.builtin.openssh_keypair:
    path: "/home/{{ item.name }}/.ssh/id_rsa"
    owner: "{{ item.name }}"
    group: "{{ item.item.name }}"
    state: present
  with_items: "{{ created_users.results }}"
  when: created_users.results | length > 0
