---
- hosts: <to_fill>
  become: true
  vars:
    node_exporter_version: "0.18.1"
  roles:
   - role: install-packages
     vars:
       packages_to_install:
         - htop
         - vim
         - less
         - ca-certificates
         - gnupg
         - htop
         - locales
         - bash-completion
         - dialog
         - procps
         - rsync
         - telnet
         - net-tools
         - iputils-ping
         - curl
         - wget
         - zip
         - apt-utils
         - apt-transport-https
         - lsb-release
         - software-properties-common
   - role: install-docker
   - role: install-node-exporter
   - role: create-tech-user
     vars:
       users_list:
         - name: techtom
   - role: create-admin-user
     vars:
       users_list:
         - name: tom
       ssh_keys:
         - { name: "tsiewruk", ssh_key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCf6sZF ... user1@example.com" }
