---
- hosts: <host>
  become: true
  vars_files:
    - vars/install-packages.yml
    - vars/install-node-exporter.yml
    - vars/user-create-tech.yml
    - vars/user-create-admin.yml
  roles:
   - role: install-packages
   - role: install-docker
   - role: install-node-exporter
   - role: user-create-tech
   - role: user-create-admin
