---
- name: Install K3S-server master node
  ansible.builtin.shell: |
    curl -sfL https://get.k3s.io | INSTALL_K3S_CHANNEL={{ k3s_version }} sh -s - server \
      --cluster-init \
      --disable servicelb \
      --disable traefik \
      --write-kubeconfig-mode 644 \
      --node-taint "node-role.kubernetes.io/master:NoSchedule"
  args:
    creates: /usr/local/bin/k3s 