---
- name: Download etcdctl
  ansible.builtin.get_url:
    url: https://github.com/etcd-io/etcd/releases/download/v{{ k3s_etcd_version }}/etcd-v{{ k3s_etcd_version }}-linux-amd64.tar.gz
    checksum: sha256:https://github.com/etcd-io/etcd/releases/download/v{{ k3s_etcd_version }}/SHA256SUMS
    dest: /tmp/etcd.tar.gz
    mode: "0644"

- name: Unpack etcdctl
  ansible.builtin.unarchive:
    src: /tmp/etcd.tar.gz
    dest: /usr/local/bin
    remote_src: true
    extra_opts:
    - --strip-components
    - 1

- name: Install K3s master node
  ansible.builtin.shell: |
    curl -sfL https://get.k3s.io | INSTALL_K3S_CHANNEL=v{{ k3s_version }} sh -s - server \
      --cluster-init \
      --disable servicelb \
      --disable traefik \
      --write-kubeconfig-mode 644 \
      --node-taint "node-role.kubernetes.io/master:NoSchedule"
  args:
    creates: /usr/local/bin/k3s

- name: Enable and start K3s service
  ansible.builtin.service:
    name: k3s
    state: started
    enabled: true
