- name: Set hostname
  ansible.builtin.hostname:
    name: "{{ inventory_hostname }}"

- name: Set timezone
  community.general.timezone:
    name: Europe/Warsaw

- name: Update packages
  ansible.builtin.yum:
    name: "*"
    state: latest

- name: Install common packages
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop:
  - epel-release
  - python3.9
  - jq
  - fail2ban
  - bash-completion
  - htop
  - firewalld
  - telnet
  - net-tools
  - iputils

- name: Configure SSH
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  loop:
  - { regexp: '^PermitRootLogin', line: 'PermitRootLogin no' }
  - { regexp: '^PasswordAuthentication', line: 'PasswordAuthentication no' }
  notify: restart ssh

- name: Configure firewalld
  ansible.posix.firewalld:
    zone: public
    state: present
    permanent: true
    target: default
  notify: Reload firewalld

- name: Enable and start firewalld
  ansible.builtin.systemd:
    name: firewalld
    enabled: true
    state: started

- name: Allow services on public zone
  ansible.posix.firewalld:
    zone: public
    service: "{{ item }}"
    state: enabled
    permanent: true
  notify: Reload firewalld
  loop:
  - ssh

- name: Configure fail2ban
  ansible.builtin.copy:
    dest: /etc/fail2ban/jail.local
    content: |
      [DEFAULT]
      # Ban IP for 10 minutes
      bantime = 600
      # 5 login attempts before ban
      maxretry = 5

      [sshd]
      enabled = true
  notify: Restart fail2ban

- name: Enable and start fail2ban
  ansible.builtin.systemd:
    name: fail2ban
    enabled: true
    state: started
